"""add password_salt column to user table

Revision ID: 58177e979e95
Revises: 5be4c279d28d
Create Date: 2022-05-16 08:21:45.100194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58177e979e95'
down_revision = '5be4c279d28d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_salt', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_salt')
    # ### end Alembic commands ###
